terrestris/shogun-gis-client

src/App.ui.spec.tsx
src/index.tsx

Change `demo eo layer`, since the old ones were very slow and sometimes unavailable.  
Might be enhanced later on.  
@terrestris/devs please check.

Change eo layer

---

src/components/ToolMenu/FeatureInfo/index.tsx
src/i18n/translations.ts

i18n for the usage hint in the `FeatureInfoPanel`

---

src/components/ToolMenu/index.tsx
src/index.tsx

This slightly restructures the initialization process of the client.
In addition the client name will be set to the document's title.
Please review @KaiVolland.

Restructure initialization of the client

---

src/components/PrintForm/index.less
src/components/PrintForm/index.tsx
src/components/ToolMenu/FeatureInfo/index.less
src/components/ToolMenu/FeatureInfo/index.tsx
src/components/ToolMenu/LayerTree/index.less
src/components/ToolMenu/LayerTree/index.tsx
src/components/ToolMenu/index.less
src/components/ToolMenu/index.tsx
src/i18n/translations.ts

This updates the styling/layout of the ToolMenu.

Layout update

---

src/components/Footer/index.less
src/components/Footer/index.tsx
src/components/Header/index.less

Make Header and Footer more responsive

---

resources/public/index.ejs

fix: lower z-index to prevent icon from overlap app elements

---

src/components/ToolMenu/LayerTree/index.less

fix: show the expand/collapse buttons in the tree

---

src/components/Footer/index.less
src/components/Footer/index.tsx

Align items and add space between label and values in Footer

---

src/components/ToolMenu/Draw/index.less
src/components/ToolMenu/Draw/index.tsx
src/components/ToolMenu/index.tsx
src/i18n/translations.ts

Added Draw Tool to Tools menu:
Now it's possible to draw a point, a line, a polygon, a circle, a rectangle and write annotations.
It also possible to modify these features, upload new ones through geojson files or delete the existing ones
Features are are not persistent.

feat(draw): added draw component and translations

---

src/components/ApplicationInfo/index.tsx
src/components/Footer/index.tsx
src/hooks/useVersion.ts
src/i18n/translations.ts

feat: implements the client version into the footer
ERM: https://redmine.intranet.terrestris.de/issues/14529

feat: client version in footer

---

src/components/ToolMenu/LayerTree/index.less
src/components/ToolMenu/LayerTree/index.tsx

Adds the library-implemented svg to point out that the layer hierarchy can be changed.

style: Toolmenu styling

---

src/components/Footer/index.less
src/components/Header/index.less
src/components/Header/index.tsx
src/components/LanguageSelector/index.less
src/components/LanguageSelector/index.tsx
src/components/ToolMenu/index.tsx
src/i18n/translations.ts

The language-selektor has been moved into the Toolbox. 
Layout for a Smartphone:
Layout for a TouchPad:

Responsive layout

---

.github/workflows/on-push-main.yml

Integrates a SonarScanner into the Pipeline

Integrate sonarqube

---

.releaserc.json

fix: activate semantic-release/github plugin

---

package-lock.json
package.json
src/components/ToolMenu/FeatureInfo/index.tsx
src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx

This forwards the Bearer token to the GFI request if needed.
Requires [#2715](https://github.com/terrestris/react-geo/pull/2715).

Fix GetFeatureInfo for internal layers

---

src/components/Header/index.less

Lines are now only broken at newline characters in the source and at [<br>] elements.

fix: defines linebreak

---

src/components/PrintForm/index.tsx

Since the jpeg export seems to be corrupt.

fix: removes jpeg from print

---

src/components/BasicMapComponent/index.tsx
src/components/Permalink/index.tsx

Permalink gets now also created out of ImageLayers.
The component refreshes automatically now since the state gets updated every time the zoomlevel, layer-composition or resolution changes.

Bugfix permalink

---

src/components/Permalink/index.tsx
src/components/ToolMenu/index.tsx

fix: toolbox is collapsed when run on phone or tablet

---

package-lock.json
package.json

Update react-i18next & jest

---

src/components/ApplicationInfo/index.tsx

Show backend version only if available

---

.eslintrc.js
package-lock.json
package.json
src/bootstrap.tsx
src/components/BasicMapComponent/index.tsx
src/components/Permalink/index.tsx
src/components/ToolMenu/FeatureInfo/FeaturePropertyGrid/index.tsx
src/components/ToolMenu/index.tsx

- fixes listener that updates the permalink when layers are added / removed from layergroups
- refactors hook dependencies and introduces rules-for-hooks via `@terrestris/eslint-config-typescript-react`
- contains a bugfix which creates the processed layer group in bootstrap.tsx in the default application. thanks @FritzHoing 

Permalink bugfixes

---

src/components/AddLayerModal/index.tsx
src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx

feat: all imported layers can be deleted now

---

package-lock.json
package.json
src/components/Header/index.tsx
src/components/ToolMenu/FeatureInfo/index.tsx
src/components/ToolMenu/index.tsx
src/plugin/index.ts
src/store/selectedFeatures/index.ts
src/store/store.ts

This adds support for the integration of plugins bound to the existing feature info component.

Add support for feature info plugins

---

package-lock.json
package.json
src/components/AddLayerModal/index.tsx
src/components/BasicMapComponent/index.tsx
src/components/Permalink/index.less
src/components/Permalink/index.tsx

- saves opacity in permalink
- adds required listeners to keep peramlink updated
- increase clickable area of permalink icon

fix: save opacity in permalink

---

src/components/Header/index.tsx

Consider the placement of the header plugin (again)

---

webpack.common.js

Fixes problems with `instanceof` checks in combination with plugins (https://github.com/terrestris/shogun-gis-client/pull/250).

fix instanceof checks

---

src/utils/getGravatarUrl.spec.ts
src/utils/getGravatarUrl.ts

Adds a Unit-Test for the getGravatarUrl-function and sets the export of the Util to default.

feat: adds unit tests

---

sonar-project.properties

.spec.ts data will now be includes in the unit-test coverage.

ci: includes spec.ts data

---

src/components/AddLayerModal/index.spec.tsx

Adds a unit-test to ensure the most basic functions.

feat: adds a unittest for the AddLayerModal

---

src/bootstrap.tsx
src/components/ApplicationInfo/index.less
src/components/ApplicationInfo/index.tsx
src/store/description/index.ts
src/store/store.ts

This suggest to render the description of the application (if any) to the info modal.

Show the application description in the `ApplicationInfo`

---

package-lock.json
package.json
src/App.less
src/components/AddLayerModal/index.tsx
src/components/Footer/index.less
src/components/Header/index.less
src/components/Permalink/index.less
src/components/Permalink/index.tsx
src/components/PrintForm/index.less
src/components/PrintForm/index.spec.tsx
src/components/PrintForm/index.tsx
src/components/ToolMenu/Draw/StylingDrawer/index.less
src/components/ToolMenu/Draw/index.less
src/components/ToolMenu/FeatureInfo/index.less
src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx
src/components/ToolMenu/LayerTree/index.tsx
src/components/ToolMenu/Measure/index.less
src/components/ToolMenu/index.less
src/components/ToolMenu/index.tsx
src/components/UserMenu/index.tsx
src/index.less
src/plugin/index.ts
src/store/toolMenu/index.ts
src/variables.less

* ⚠️ BREAKING CHANGE ⚠️ Replace `Menu` by `Collapse`
*  Get rid of dirty hack while mapfish print initialization within a menu item, move logic to the `PrintForm`
*  Get rid of some antd deprecations
*  See also https://github.com/terrestris/react-geo/pull/3006
* Replace less variables (`@`) by CSS variables

Tool menu refactoring

---

.github/workflows/on-release.yml
.github/workflows/release.yml
README.md
babel.config.js
package.json
tsconfig.json

This adds the previously missing less files to the npm-distributed files.
In addition the outdated image name has been updated in the README.

Add less files to distributed build

---

src/components/ToolMenu/index.less
src/components/ToolMenu/index.tsx

- removes max hight of content box
- removes custom icon transform due to incompatible icons

style: adjustments of the toolbar

---

src/index.less

Title says it all.
@terrestris/devs

fix: prevent scrollbar on viewport body

---

package-lock.json
package.json
src/components/PrintForm/CustomFieldInput/index.tsx
src/components/PrintForm/Serializer/SHOGunMapFishPrintV3TiledWMSSerializer.ts
src/components/PrintForm/Serializer/SHOGunMapFishPrintV3WMSSerializer.ts
src/components/PrintForm/index.tsx
src/i18n/translations.ts

Update to mapfish print manager V8

---

src/components/ToolMenu/index.less

closes https://github.com/terrestris/shogun-gis-client/issues/599

fix: menu width when collapsed

---

src/components/AddLayerModal/index.less
src/components/AddLayerModal/index.tsx
src/i18n/translations.ts

This checks url input for the search params  
- request
- version
- service  
and adds them if needed.  
+ adds version select box
+ some layout adaptions (spaces)

feat: add completion if url and add version select

---

src/bootstrap.tsx

Empty tool configurations will now be replaced with the full list of available tools.

fix: adds a check for array length

---

src/components/ToolMenu/FeatureInfo/index.tsx

* Exclude inivisible layers
* Query only WMS based layers

fix: enhance layer filter for feature info tool

---

.github/workflows/release.yml
.gitignore
Dockerfile.e2e
e2e-tests/auth.setup.ts
global-setup.ts
package-lock.json
package.json
playwright.config.ts

Playwright setup:
- custom user logins
- creates a e2e-testing image 
- custom process.env variables

Playwright

---

.github/workflows/release.yml

- renaming the jobs
- using new Dockerfile

fix: fixing playwright workflow

---

package.json

Remove e2e-tests from check scrip temporally since they will be tested separately in a follow up.

Fix build pipeline

---

src/components/ToolMenu/FeatureInfo/index.tsx

More or less a follow up of !749:
Use more robust check to properly update queryable layer array on layer visibility change via layer tree.

fix: use more robust check for layer visibility change

---

package-lock.json
package.json
src/bootstrap.tsx

This handles a optional param `defaultLanguage` (shogun `clientConfig`) and updates shogun-util accordingly.
@terrestris/devs :pray:

feat: handle defaultLanguage config

---

src/bootstrap.tsx
src/i18n/index.ts

Reverts terrestris/shogun-gis-client#815
Required as the commit messages were squashed.

Revert "Fix i18n initialization"

---

src/bootstrap.tsx
src/i18n/index.ts
src/plugin/index.ts

Fix i18n init

---

package-lock.json
package.json
src/components/PrintForm/index.tsx

- bump mapfish print manager to 9.0.1
- rm unneeded await
@terrestris/devs :pray:

Update mp print manager

---

src/components/Footer/index.less
src/components/Footer/index.tsx
src/plugin/index.ts

The footer can now be extended via plugins.

fix: makes the footer extendable via plugins

---

src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/utils/generateSolrQuery.spec.ts
src/utils/generateSolrQuery.ts

- improves error handling when no editFormConfig is configured for an editable layer
- adjust search filter

small bugfixes for search and feature editing

---

package-lock.json
package.json

chore: update shogun-util to 5.6.1

---

package-lock.json
package.json
src/components/WmsTimeSlider/index.tsx

* Update ol-util v11.0.0
* Get rid of stream and timers dependencies
* Remove obsolete check for dimensions on WMSTime layers
* Update react-geo v22.4.1
* Use version with pinned ol and ol-util versions
* Compare https://github.com/terrestris/react-geo/releases/tag/v22.4.1
* Update shogun-util v5.6.2

Update @terrestris packages

---

package-lock.json
package.json
src/bootstrap.tsx
src/components/DisplayField/index.tsx
src/components/JsonModal/index.less
src/components/JsonModal/index.spec.tsx
src/components/JsonModal/index.tsx
src/components/ToolMenu/FeatureInfo/FeatureInfoForm/index.tsx
src/i18n/translations.ts
webpack.common.js

This initializes the `JsonModal` component displaying any JSON content given in the `FeatureInfoForm`.

Init the `JsonModal` component

---

global-setup.js
src/e2e-tests/auth.setup.ts
src/e2e-tests/draw-annotation.spec.ts
src/e2e-tests/draw.spec.ts
src/e2e-tests/drawCircle.spec.ts
src/e2e-tests/drawDelete.spec.ts
src/e2e-tests/drawEdit.spec.ts
src/e2e-tests/drawExport.spec.ts
src/e2e-tests/drawLine.spec.ts
src/e2e-tests/drawModifyColorScheme.spec.ts
src/e2e-tests/drawPoint.spec.ts
src/e2e-tests/drawPolygon.spec.ts
src/e2e-tests/drawRectangle.spec.ts
src/e2e-tests/drawUpload.spec.ts
src/e2e-tests/exportPrint.spec.ts
src/e2e-tests/footer.spec.ts
src/e2e-tests/header.spec.ts
src/e2e-tests/languageSelector.spec.ts
src/e2e-tests/layertree.spec.ts
src/e2e-tests/measure.spec.ts
src/e2e-tests/queryMapFeatures.spec.ts
src/e2e-tests/scaleCombo.spec.ts
src/e2e-tests/searchBar.spec.ts
src/e2e-tests/share.spec.ts
src/e2e-tests/userMenu.spec.ts
tsconfig.json

- rename tests
- test setup-configuration adjustments

Testsetup fix

---

playwright.config.js

fix: remove unneded comment

---

Dockerfile.e2e

Fixes the path of the testfile-directory

Dockerfile test-path

---

src/components/EditFeatureDrawer/EditFeatureForm/index.tsx
src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/components/FileUpload/index.tsx
src/components/ImageUpload/index.tsx
src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx
src/hooks/useWriteWfsTransaction.ts

Fixes some issues from https://github.com/terrestris/shogun-gis-client/pull/1124 More details can be found in the commit messages / review comments.

File upload improvements

---

README.md
package-lock.json
resources/config/gis-client-config.js
src/components/MultiSearch/index.tsx
src/global.d.ts

Allows to configure the solr search:
| Name | Description | Default |
| ---- | ----------- | ------- |
| search.solrBasePath | Base path to a solr instance. | '/search/query' |
| search.coreName | Solr core name. | 'search' |
| search.defaultUseViewBox | Whether the search is restricted to the current view box. | true |
| search.useNominatim | Whether to use Nominatim. | true |
| search.useSolrHighlighting | Enable / disable solr search result highlighting. | true |
| search.delay | Delay in milliseconds before search is triggered (debouncing). | 1000 |
| search.minChars | Minimum search term length for the search to be triggered. | 3 |
| search.solrQueryConfig.queryParser | Solr query parser. Must be either 'lucene', 'dismax' or 'edismax' | 'edismax' |
| …

Make search parameters configurable

---

src/plugin/README.md

chore: adds guide for plugin development

---

Dockerfile.e2e
playwright.config.js

- Updating playwright image
- removing unsupported browsers
- fixing output path

Fixing Setup

---

src/components/ToolMenu/FeatureInfo/index.tsx

feat: sort GFI tabs by position in the layer tree

---

src/components/DisplayField/index.tsx
src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/components/FileUpload/index.tsx
src/components/ImageUpload/index.tsx
src/hooks/useWriteWfsTransaction.ts

- allows to display a list of uploaded files and images in GFI
- fixes file path check
- use thumbnail URLs for image files
- minor improvements

Show uploaded files in GetFeatureInfo-Panel

---

src/components/DisplayField/index.tsx

Disable grouping in DisplayField

---

src/components/DisplayField/index.tsx
src/components/PrintForm/OutputFormatSelect/index.spec.tsx

Fix for https://github.com/terrestris/shogun-gis-client/pull/1210#discussion_r1340163684

Consider currently active language when formatting numbers

---

src/components/AddLayerModal/index.less
src/components/AddLayerModal/index.tsx
src/i18n/translations.ts

Implement an URL validation.
Whenever an invalid URL is used, a short information will be displayed.

URL Validation

---

src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/components/EditFeatureDrawer/SaveButton/index.tsx

This PR introduces error handling for form validation in the `EditFeatureFullForm` and `SaveButton` components to enhance the application's error management during form
validation.
In the `EditFeatureFullForm` component:
- added a function to format error messages for field validation
- modified the `onSaveError` function to handle different error types and display formatted error messages when validation fails
In the `SaveButton` component:
- implemented error handling by calling the `onError` function when form validation fails

Enhance error handling for form validation

---

src/components/EditFeatureDrawer/EditReferenceTable/index.tsx

This PR is a follow up to https://github.com/terrestris/shogun-gis-client/pull/1332 and fixes an error where thumbnails of images weren't shown anymore and the preview of images wasn't accessible.

Convert image uploads to base64 and handle URLs

---

src/components/AddLayerModal/index.tsx
src/components/ToolMenu/LayerTree/LoadingIndicator/index.less
src/components/ToolMenu/LayerTree/LoadingIndicator/index.tsx
src/components/ToolMenu/LayerTree/index.tsx
src/components/ToolMenu/index.less

- Fixes the listener for image layer
- Change loading animation

fix: refactor loading animation

---

src/bootstrap.tsx
src/i18n/translations.ts

Show permission denied message for applications that are not public

---

package-lock.json
package.json
src/App.tsx
src/components/CookieBanner/index.less
src/components/CookieBanner/index.tsx
src/components/JsonModal/index.tsx
src/i18n/translations.ts
src/plugin/index.ts

This PR introduces a cookie banner consent and fixes some eslint code warnings.
https://github.com/terrestris/shogun-gis-client/pull/486 is closed in favor of this PR.

Introduce cookie consent

---

src/components/PrintForm/LayoutSelect/index.tsx
src/components/PrintForm/index.tsx

This PR resets the dpi field in the print manager when the value of layout has been changed to another layout.

Resets the dpi field when changing the layout

---

src/components/ToolMenu/Draw/index.tsx

This fixes a bug where when uploading a corrupt (Geo)JSON file the website would crash. Additionally added a new function that checks the viability of the uploaded file. This should enhance the readability of the code.

fix: prevents the application from crashing when a corrupt file is uploaded

---

src/components/LayerDetailsModal/index.tsx

fix: switch tooltip text for internal configuration

---

src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.less

Eine kleine Anpassung der Höhe der Toolbar, sodass diese nicht mehr auf 100% ist.

fix: fixing the height of the EditFeatureGeometryToolbar

---

src/components/AddLayerModal/index.tsx
src/components/EditFeatureDrawer/EditFeatureForm/index.tsx
src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/components/EditFeatureDrawer/EditReferenceTable/index.tsx
src/components/EditFeatureDrawer/SaveButton/index.tsx
src/components/FileUpload/index.tsx
src/components/Header/index.tsx
src/components/ImageUpload/index.tsx
src/components/LayerDetailsModal/index.less
src/components/MultiSearch/index.tsx
src/components/PrintForm/ScaleSelect/index.tsx
src/components/PrintForm/Serializer/SHOGunMapFishPrintV3TiledWMSSerializer.ts
src/components/PrintForm/index.tsx
src/components/SearchField/index.tsx
src/components/ToolMenu/Draw/Attributions/index.tsx
src/components/ToolMenu/FeatureInfo/index.tsx
src/e2e-tests/auth.setup.ts
src/hooks/useExecuteGetFeature.ts
src/hooks/useExecuteWfsDescribeFeatureType.ts
src/hooks/useExecuteWfsTransaction.ts
src/hooks/useExecuteWfsTransactionLock.ts
src/hooks/useWriteWfsTransaction.ts

This PR refactors several files and attempts to fix some code smells detected by SonarQube.
Please review.

Fix several code smells

---

src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
src/components/EditFeatureDrawer/SaveButton/index.tsx
src/i18n/translations.ts

An error message is shown when trying to save a feature without geometry.

Show error message for missing geometry

---

src/e2e-tests/auth.setup.ts

This fixes the strict mode violation.

E2E authentication error

---

src/utils/generateSolrQuery.spec.ts
src/utils/generateSolrQuery.ts

Allow to search for numeric values

---

package-lock.json
package.json
src/components/ToolMenu/FeatureInfo/FeatureInfoTabs/index.less
src/components/ToolMenu/FeatureInfo/FeatureInfoTabs/index.tsx
src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx
src/components/ToolMenu/FeatureInfo/index.less

This updates react-geo to the latest version.
It also updates some styling in the gis client to gain some space and create a cleaner look.

FeatureInfoPanel updates

---

src/components/UserMenu/index.tsx

Hide user chip in public applications

---

src/components/DisplayField/index.spec.tsx
src/components/DisplayField/index.tsx

This creates anchor elements (`<a href="" />`) elements for values that seem to be links.

Create anchor elements for linklike values in DisplayField

---

src/components/UserMenu/index.less
src/components/UserMenu/index.tsx
src/i18n/translations.ts

This MR adds a documentation Button for the gis-client documentation.
Please note:
the following MR needs to be merged first so that the documentation is accessible:
https://github.com/terrestris/shogun-docker/pull/118

Documentation Button

---

src/components/DisplayField/index.spec.tsx
src/components/DisplayField/index.tsx

This reverts the creation of links for urls targeting the local file system as this is blocked by the browse anyway.

Removes link creation to urls with local target

---

src/bootstrap.tsx
src/components/ToolMenu/index.less

Change/adds background color in active header item in ToolMenu and also adds auto-adjustability of complementary color contrast in order to improve visibility of text on different color backgrounds.

feat: adds auto-adjustability of colors  in ToolMenu

---

src/bootstrap.tsx
src/components/PrintForm/index.tsx
src/store/print/index.ts

Gives the possibility to add several templates for the print tool. Each app therefore has the possibility of having a combination different templates.

feat: creates ability to select app specific print templates

---

.github/workflows/update-coverage.yml
README.md
package-lock.json
package.json

Replaces the mechanism introduced in https://github.com/terrestris/shogun-gis-client/commit/01e6b6fcd2514c34a0b9f595b133ecd0d28d7763 with https://github.com/terrestris/watch-build-copy
Resolves #457

Replace watch-build script

---

.github/workflows/on-push-main.yml

This MR ensures that merging from dependabot does not send a report to sonarqube

Sonar-Scan

---

.github/workflows/on-push-main.yml
sonar-project.properties

This merge request changes the github-action used for the SonarQube-Scan. It now uses the official SonarQube Scan Action (https://github.com/marketplace/actions/official-sonarqube-scan).

ci: update sonarqube scanner action

---

.github/workflows/update-coverage.yml

This merge request makes a minor change to the update-coverage workflow. This change makes sure special characters in the jest-html-report are handled correctly. They can then be inserted into the Readme-file.

ci: minor fix to handle special characters in coverage html

---

.github/workflows/on-pull-request.yml
.github/workflows/update-coverage.yml

See title.
@devs Please review

Skip coverage jobs for dependabot PRs

---

.github/workflows/on-pull-request.yml

Escape github action conditions

---

resources/config/gis-client-config.js
src/components/UserMenu/index.tsx
src/global.d.ts

depends on: https://github.com/terrestris/shogun-docker/pull/163

feat: adds a config for documentation button

---

package-lock.json
package.json
src/components/ToolMenu/Draw/Attributions/index.tsx
src/components/ToolMenu/Draw/index.tsx

depends on: https://github.com/terrestris/react-geo/pull/3977

fix: open attribute drawer on feature select and pass selected feature

---

src/components/ToolMenu/FeatureInfo/index.tsx

fix: migrate featureinfo

---

src/components/ApplicationInfo/index.spec.tsx
src/components/DisplayField/index.spec.tsx
src/components/EditFeatureDrawer/EditReferenceTable/index.spec.tsx
src/components/JsonModal/index.spec.tsx
src/components/Permalink/index.spec.tsx

All tests from https://github.com/terrestris/shogun-gis-client/commit/1da9fcd0985fbe889a6fcb19d2eb4e884b55d0b8#diff-e71476190a530b48c719dab9617e8ededbe3a7a7154cfecb0e55bf7af35b8f1a fixed, except the one for the checkbox.

test: fix broken tests

---

.github/workflows/on-pull-request.yml
.github/workflows/on-push-main.yml
jest.config.js
src/components/EditFeatureDrawer/DeleteButton/index.spec.tsx
src/components/EditFeatureDrawer/EditFeatureForm/index.spec.tsx
src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.spec.tsx

This updates existing Unittests for the EditFeatureDrawer (form, delete button, and edit geometry toolbar).
Additionally unittests are excluded from the coverage scan in the jest.config and the coverage reporting in a github-comment is fixed.

test: update unittests for EditFeatureDrawer

---

src/components/ToolMenu/FeatureInfo/index.tsx

This fixes the broken feature info tool by adjusting the `CoordinateInfo` component to the latest changes in react-geo.

Fix white screen in feature info tool

---

src/bootstrap.tsx
src/components/DocumentationButton/index.tsx
src/components/Header/index.less
src/components/ToolMenu/index.less
src/components/UserMenu/index.less

fix: layout and styling

---

src/bootstrap.tsx
src/components/ToolMenu/LayerTree/index.less
src/components/ToolMenu/LayerTree/index.tsx
src/store/layerTree/index.ts

feat: adds icons to indicate searchable, hoverable and/or editable layer

---

src/bootstrap.tsx
src/components/Header/index.less
src/components/ToolMenu/index.less

Shogun gis client layout fixes

---

src/bootstrap.tsx
src/components/RerouteToLogin/index.less
src/components/RerouteToLogin/index.tsx
src/index.less

fix: adds padding and extends link to the text

---

package.json

Just add a npm script entry for the watchBuild script

Watch buildto script entry

---

src/i18n/translations.ts

Set correct translation key

---

src/components/ToolMenu/LayerTree/index.tsx

Ensure an object is passed to the `Legend`

---

src/bootstrap.tsx
src/components/ApplicationInfo/index.tsx
src/components/EditFeatureDrawer/EditFeatureForm/index.tsx
src/components/EditFeatureDrawer/EditReferenceTable/index.tsx
src/components/Footer/index.tsx
src/components/Header/index.tsx
src/components/MapToolbar/index.tsx
src/components/PrintForm/index.tsx
src/components/ToolMenu/Draw/Attributions/index.tsx
src/components/ToolMenu/FeatureInfo/FeatureInfoForm/index.tsx
src/components/ToolMenu/index.tsx
src/components/UploadDataModal/index.tsx
src/components/UserMenu/index.tsx
src/hooks/searchEngines/useNominatimSearchEngine.ts
src/hooks/useConvertImageUrl.ts
src/hooks/useWriteWfsTransaction.ts
src/store/legal/index.ts

Title says it all, please review.

Fix several code smells detected by SonarQube

---

src/bootstrap.tsx
src/components/ToolMenu/index.tsx

This fixes two issues reported by Sonarqube (reliability):
https://sq.terrestris.de/project/issues?impactSeverities=MEDIUM&impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&open=621b3837-0375-41da-82d6-133f717c10ff&id=shogun-gis-client
https://sq.terrestris.de/project/issues?impactSeverities=MEDIUM&impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&open=4add146d-109a-4985-98b5-13acc29c3b93&id=shogun-gis-client

fix: minor issues reported by sonarqube

---

src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.spec.tsx

Adds a unittest for the LayerTreeContextMenu.

test: add unittest for LayerTreeContextMenu

---

package-lock.json
package.json
src/components/ToolMenu/Measure/index.tsx

fix(measure): use geodesic measurements only for sperical projections

---

src/components/ToolMenu/Draw/StylingDrawerButton/StylingComponent/index.spec.tsx

Adds a unittest for the StylingComponent.

test: unittest for StylingComponent

---

src/components/DocumentationButton/index.spec.tsx

This adds a unittest for the component DocumentationButton.

test: add unittest for DocumentationButton

---

src/bootstrap.tsx
src/components/ApplicationInfo/index.tsx
src/components/EditFeatureDrawer/EditReferenceTable/index.tsx
src/components/ReferenceTable/index.tsx
src/components/ToolMenu/LayerTree/index.tsx
src/components/ToolMenu/index.tsx
src/hooks/searchEngines/useSolrSearchEngine.ts
src/hooks/searchEngines/useWfsSearchEngine.ts
src/hooks/useConvertImageUrl.ts
src/hooks/useExecuteWfsTransactionLock.ts
src/hooks/useWriteWfsTransaction.ts
src/store/featureInfo/index.ts
src/store/layerTree/index.ts

This fixes a number of issues reported by SonarQube:
https://sq.terrestris.de/project/issues?id=shogun-gis-client&issueStatuses=OPEN%2CCONFIRMED

fix: issues reported by SonarQube

---

src/bootstrap.tsx
src/store/store.ts

This PR collects all reducers of the used plugins before replacing the original reducer.  
Please review

fix: collect all plugin reducers
