src/components/ToolMenu/FeatureInfo/index.tsx
This suggests to pass the flat list of layers to the `CoordinateInfo` as the internal filter didn't check for group layer contents.
Please review @KaiVolland.
=> Pass flat layers array to the `CoordinateInfo`

resources/public/fallbackConfig.js, resources/public/index.ejs, src/App.ui.spec.tsx, src/global.d.ts, src/index.tsx, src/store/title/index.ts, webpack.common.js
This introduces a configuration file for the client that can be used to set global options (currently the `appPrefix` is available only).
Please review @KaiVolland.
=> Introduce client configuration file

antd.theme.js, babel.config.js, package-lock.json, package.json, src/App.less, src/App.tsx, src/components/Footer/index.less, src/components/Header/index.less, src/components/Header/index.tsx, src/components/ToolMenu/LayerTree/index.less, src/components/ToolMenu/index.less, src/index.less, src/index.tsx, src/store/logoPath/index.ts, src/store/store.ts, webpack.common.js, webpack.prod.js
This introduces the parsing/handlig of SHOGuns theming feature:
Compare https://github.com/terrestris/shogun/pull/521
=> Implement handling for theming

src/components/PrintForm/index.tsx
This MR suggests to use `window.open` instead of `printManager.download` which sets `window.locatio.href`.
=> Open print in new browser tab

resources/public/index.ejs, src/global.d.ts, src/index.tsx, src/util/GeoServerUtil.ts
This introduces the `GeoServerUtil` and adds an clientConfig option (`loginToGeoServer`) to log into the geoserver automatically.
:exclamation: This also changes the path of the client-config to be aligned with the admin-client-config.js
=> GeoServerUtil and optional GeoServer login

src/App.tsx, src/components/AddLayerModal/AddLayerModal.less, src/components/AddLayerModal/AddLayerModal.tsx, src/components/ToolMenu/index.tsx, src/i18n/translations.ts, src/store/addLayerModal/index.ts, src/store/store.ts
This adds the `addLayerModal` component, based on `react-geo` [AddWmsPanel](https://terrestris.github.io/react-geo/docs/latest/#/Components/Containers/AddWmsPanel) .
Thanks @dnlkoch for finishing and review.
=> feat: add addLayerModal

resources/config/gis-client-config.js, src/global.d.ts, src/index.tsx
This makes the keycloak `onLoad` behavior configurable via `gis-client-config.js`:
- `check-sso` allows anonymous access without login
- `login-required` always redirects to keycloak login
For more details see the keycloak documentation: https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter
Co-authored-by: Daniel Koch <koch@terrestris.de>
=> feat: make keycloak `onLoad` action configurable

src/components/ToolMenu/Draw/index.less, src/components/ToolMenu/Measure/index.less
Increases distance between svg and string of the Toolbar-Children.
=> refactor: Toolbar-Styling

src/App.tsx
The `Permalink` panel was rendered below the map as well.
Please note @terrestris/devs.
=> Remove unneeded `Permalink` panel from the `App`

src/components/ToolMenu/index.tsx
This fixes the print for internal layers by passing the keycloak client (if present) to the bearer token header generator.
=> Fix print for internal layers

src/components/ToolMenu/index.tsx, src/components/UserMenu/index.tsx
This fixes two console warnings by:
- fixing a potential duplicated usage of a key.
- replacing the direct usage of `<Menu.Divider />` with ` type: 'divider'`.
=> Fix console warnings about component usage

src/components/Header/index.less
changes the @media query from min to max, so that the browser screen will not be handled as a tablet.
=> fix: adjusts the @media query

src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/i18n/translations.ts
The WMS-layers could not be removed because the variable targetFolderName was assigned to a wrong name, so targetGroup was undefined.
Thus the unneeded key value pair externalWmsFolder: 'External services' was deleted.
=> fix: assigns the correct name to identify the layer

.github/workflows/release.yml, CHANGELOG.md, README.md, package-lock.json, package.json
Since the repository contains not just a demo, but the default GIS client for the SHOGun backend, this suggests to rename the project to `@terrestris/shogun-gis-client`.
**Breaking:**
- All upcoming docker images will be named accordingly: `nexus.terrestris.de/repository/terrestris-public/shogun-gis-client`. Please adjust your images usages in docker-compose setups and deploy pipelines.
- The repository url will be changed to `https://github.com/terrestris/shogun-gis-client` after this PR has been merged. Even if GitHub provides a redirct, I would suggest to adjust your checkouts.
=> Rename to `@terrestris/shogun-gis-client`

.dockerignore, .github/workflows/on-pull-request.yml, .github/workflows/on-push-main.yml, .github/workflows/on-release.yml, .github/workflows/release.yml, .gitignore, .releaserc.json, Dockerfile, package.json, src/global.d.ts, src/hooks/useVersion.ts, src/store/addLayerModal/index.ts, tsconfig.json, webpack.common.js
This suggests to publish the artifact files (built via `tsc`) to the npm registry.
The published files can be useful for external apps, especially plugins (see #250), to make use of the typings, utils and others.
~TODO: The name of the project should be adjusted first, see #274.~
=> Publish artifact files to npm

package.json
This sets the `publishConfig` as suggested in [#512](https://github.com/semantic-release/semantic-release/issues/512) to fix the first npm deployment that is [currently failing](https://github.com/terrestris/shogun-gis-client/runs/7968124373?check_suite_focus=true#step:6:1086).
Please note @terrestris/devs.
=> Set `publishConfig` in package.json

src/components/BasicMapComponent/index.tsx, src/components/Permalink/index.less
.getVisible()-condition is not needed here.
Changes in index.less adjust the CSS in responsive design.
=> Permalink adjustments

src/components/Header/index.tsx, src/plugin/index.ts
This adds support for integrating plugins to the header bar.
Example:
```
const MyHeaderPlugin: ClientPlugin = {
key: 'my-header-plugin',
integration: {
placement: 'header',
placementOrientation: 'right',
insertionIndex: 0
},
component: MyPlugin,
i18n: i18n
};
```
=> Add support for header plugins

src/bootstrap.tsx, src/global.d.ts
This optimizes the handling of a client plugin with multiple exposed paths by loading the source file only once.
The configuration has slightly changed (and became simpler) which might be considered as a breaking change, but as the plugin feature is treated as experimental, I suggest to handle it as a fix.
Before:
```js
plugins: [{
name: 'MyAppPlugin',
exposedPath: './ExposedSubPathOne',
resourcePath: '/client-plugins/index.js'
}, {
name: 'MyAppPlugin',
exposedPath: './ExposedSubPathTwo',
resourcePath: '/client-plugins/index.js'
}]
```
After:
```js
plugins: [{
name: 'MyAppPlugin',
exposedPaths: [
'./ExposedSubPathOne',
'./ExposedSubPathTwo'
],
resourcePath: '/client-plugins/index.js'
}]
```
=> Optimize loading of plugins with multiple exposed paths

.github/workflows/release.yml
Switches to docker-public.terrestris.de so the image will be available publicly.
@terrestris/devs Please note.
=> use docker-public.terrestris.de registry

src/bootstrap.tsx, src/components/AddLayerModal/index.tsx, src/components/BasicMapComponent/index.tsx, src/components/Permalink/index.tsx, src/components/ToolMenu/LayerTree/index.tsx
A new permalink is generated every time the zoom-level, the extent or the layer constellation changes.
This MR removes all project specific components out of the GIS-client and let's the GIS-client handle new imports in a generalized way.
=> feat: generates a new permalink whenever a layer is added

README.md, jest.config.js, resources/config/gis-client-config.js, src/components/Permalink/index.tsx, src/components/ToolMenu/index.tsx, src/global.d.ts
This makes the url to the print servlet configurable via the `gis-client-config.js`
=> Add print url to client config

src/components/BasicNominatimSearch/index.tsx
This adds the `viewbox` param to `Nominatim` search query if the given mapView extent is set.
cf. https://nominatim.org/release-docs/develop/api/Search/#parameters
**Reason**: Avoid search results which are outside the defined mapView and can not be displayed on the map anyway.
@terrestris/devs please check.
=> feat: Nominatim: add viewbox config if extent is given

src/bootstrap.tsx
Instead of being invisible per default, the layer-group is only invisible as long as no other layers are within that layer-group.
=> fix: layergroup hiding in layertree

.eslintrc.js, jest.config.js, package-lock.json, package.json, src/App.spec.tsx, src/components/AddLayerModal/index.spec.tsx, src/components/ApplicationInfo/index.spec.tsx, src/components/Footer/index.spec.tsx, src/components/Header/index.spec.tsx, src/components/PrintForm/CustomFieldInput/index.spec.tsx, src/components/PrintForm/LayoutSelect/index.spec.tsx, src/components/PrintForm/OutputFormatSelect/index.spec.tsx, src/components/PrintForm/ResolutionSelect/index.spec.tsx, src/components/PrintForm/index.spec.tsx, src/components/ToolMenu/index.tsx, src/global.d.ts, src/utils/testUtils.tsx, webpack.common.js
- adds some unit tests (Footer, PrintForm and related components)
- adds user-event and updates some dependencies
- adds util `createReduxWrapper`
- fixes linting problems
- changes eslint rule `object-curly-newline` to `consistent` with `minProperties: 2`. See https://eslint.org/docs/latest/rules/object-curly-newline
=> add unit tests for print components and footer

src/App.tsx
This suggest to disable the `BackgroundLayerChooser` as it seems to be broken right now (see #485) and:
- There is no way to define the required property `isBackgroundLayer` in shogun nor the shogun-admin.
- There seems to be a conflict by setting it to a layer that is also visible in the tree (the layer _must_ be visible in the tree to be catched up by the chooser).
- There seems to be a request loop once a layer is activated in it.
=> Disable the `BackgroundLayerChooser`

src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx
This fixes the zoom-to-layer option in the tree context menu by sending the authentication header if needed.
=> Fix zoom-to-layer

src/components/BasicMapComponent/index.tsx, src/plugin/index.ts
This adds support for plugins rendered inside the map div.
Requires [#3008](https://github.com/terrestris/react-geo/pull/3008) (react-geo).
=> Add support for map plugins

src/components/ToolMenu/index.less
=> fix: avoid scrollbar on collapsed menu

src/bootstrap.tsx, src/components/AddLayerModal/index.tsx, src/components/BasicMapComponent/index.tsx, src/components/Permalink/index.tsx, src/components/ToolMenu/Draw/StylingDrawer/StylingComponent/index.tsx, src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/components/ToolMenu/LayerTree/index.tsx, src/index.less
This fixes several issues while using external layers in the permalink:
- Fix removal of external links
- the external layer folder will be removed if no external layer is available anymore
- layers can be removed from whatever folder they have been dragged to
- Flip the add all and add selected buttons in the add external layers modal
- Set the layer visibility as given in the permalink
=> Several fixes for external layers in permalinks

src/components/ToolMenu/index.less, src/components/ToolMenu/index.tsx
If one closes the measure tools panel, its interactions will be disabled.
Besides, active measure and draw tools are highlighted a bit with a bigger font size.
=> fix(issue): disable measure tools when panel collapses, highlight active tool

src/components/ToolMenu/Draw/index.less, src/components/ToolMenu/Measure/index.less, src/components/ToolMenu/index.less
This makes the icons and texts appear uniform.
Before:
After:
@mholthausen @hblitza please review
=> fix(layout): fix menu icons and text positioning

src/components/ToolMenu/Measure/index.tsx, src/components/ToolMenu/index.tsx
This PR fixes a conflict between the measurement tools and the export (print) panel where the measuring tools remain active when opening the print tool and thus led to a conflict when selecting the print frame and vice versa
=> Fix a conflict between measurement tools and the export (print) panel

src/components/ToolMenu/LayerTree/index.less, src/components/ToolMenu/LayerTree/index.tsx
This adds a loading indicator to layers to give a better user experience.
Some layer sources, like OSM, may have a flickering effect as their loading state cannot always be determined completely.
=> feat: add layer loading indicator to tree

package-lock.json, package.json
fyi, fixes issue when printing on devices with device-pixel-ratio != 1 (e.g. iPad)
=> feat: updating mapfish-print-manager

src/App.less, src/bootstrap.tsx
Set custom style (defined via CSS variables `--primaryColor`, `--secondaryColor` and `--complementaryColor`) on document body to make its values accessible for elements which are placed outside of `#app` div (e.g. drawer or modals)
=> feat: set custom theme on document body

src/bootstrap.tsx, src/components/Footer/index.tsx
* Pass projection string to layer tree parser, otherwise the [default](https://github.com/terrestris/shogun-util/blob/main/src/parser/SHOGunApplicationUtil.ts#L260) `EPSG:3857` CRS will always be assumed for all layers, what is obviously wrong for applications based on any projection beside Pseudo-Mercator
* Show coordinates of mouse position in configured map CRS (previously hardcoded to EPSG:25832)
=> Consider app projection while parsing layers

package-lock.json, package.json
This PR updates the mapfish-print-manager to version 8.0.2
=> Bump mapfish-print-manager from 8.0.1 to 8.0.2

package-lock.json, package.json, src/bootstrap.tsx, src/components/Footer/index.spec.tsx, src/components/Footer/index.tsx, src/components/ToolMenu/Draw/StylingDrawer/StylingComponent/index.tsx, src/store/legal/index.ts, src/store/store.ts
This PR lets the map client use the configuration of the legal links for the footer, when available. If this setting is not specified for a client, the already existing defined links are used as default.  
Needs https://github.com/terrestris/shogun/pull/642 and https://github.com/terrestris/shogun-util/pull/254 first be merged.
Also included is some code styling by eslint.
=> Use legal links config

src/components/PrintForm/index.tsx, src/components/ToolMenu/index.tsx
Don't pass `client` as prop to `PrintForm`, use `useSHOGunAPIClient()` instead.
=> breaking: remove client prop, get client from hook instead

.github/workflows/release.yml
merge two workflows so that the building process of the e2e image has access to all variables like `steps.semantic.outputs.new_release_published == 'true'`
=> fix: fixing playwright workflow

src/components/ToolMenu/FeatureInfo/index.tsx
Remove unnecessary check for layer visibility which actually breaks GFI tool functionality for the following use case:
- start client
- request some visible queryable layer -> GFI grid is shown
- turn some another queryable layer visible via checkbox in layer tree
- request this layer -> infos are not shown / GFI request is missing
=> fix: remove unnecessary layer visibility check for GFI tool

README.md, package-lock.json, package.json, resources/config/gis-client-config.js, src/App.tsx, src/components/BasicMapComponent/index.tsx, src/components/Permalink/index.tsx, src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/components/ToolMenu/index.less, src/components/ToolMenu/index.tsx, src/components/UploadDataModal/index.less, src/components/UploadDataModal/index.spec.tsx, src/components/UploadDataModal/index.tsx, src/global.d.ts, src/i18n/translations.ts, src/store/store.ts, src/store/uploadDataModal/index.ts, webpack.common.js
This adds a modal for uploading shape- and geotiff files to the specified GeoServer.
Per default the upload is available for admin users only. If you want to allow upload for other user roles, note the given configuration `authorizedRoles` and ensure the [rest interfaces in GeoServer](https://docs.geoserver.org/stable/en/user/security/rest.html) are accessible for the users. An example `rest.properties` allowing the upload for users with the `ROLE_USER` could look like the following:
```properties
/rest/workspaces/shogun/datastores/*/file.shp;PUT=ROLE_USER,ROLE_ADMINISTRATOR
/rest/workspaces/shogun/datastores/*/featuretypes;POST=ROLE_USER,ROLE_ADMINISTRATOR
/rest/workspaces/shogun/coveragestores/*/file.geotiff;PUT=ROLE_USER,ROLE_ADMINISTRATOR …
```
=> feat: allow shape and geotiff upload

src/bootstrap.tsx, src/i18n/index.ts
Follow-up fix of #813 :  
If `defaultLanguage` is set, no LanguageDetector should be use.  
Then the initialization of i18n must be done **after** `LanguageDetector` plugin has been added.  
Big Thanks to @dnlkoch 
@terrestris/devs
=> Fix i18n initialization

README.md, src/components/PrintForm/index.tsx
One or more print apps of specific language where `print app name === languageCode`.
When initializing the print manager, check if print apps has an app that has the same name as the current language code and set it as active print app.
@terrestris/devs what do you think?
=> feat: use print app of current language code

src/components/UserMenu/index.tsx
This adjusts the items available in the user menu based on the following conditions:
- only shows "login" item if keycloak is enabled
- only shows "manage profile" item if user has `manage-account` role in `account` keycloak client
=> feat: compose user menu dynamically

src/bootstrap.tsx
This fixes the reloading loop in some browsers (e.g. Firefox) by disabling checking the login status in an iframe.
See [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#session-status-iframe) for further details.
=> Disable checking login status in iframe

src/bootstrap.tsx, src/components/Header/index.less, src/components/Header/index.tsx, src/components/MultiSearch/index.less, src/components/MultiSearch/index.spec.tsx, src/components/MultiSearch/index.tsx, src/components/SearchField/index.less, src/components/SearchField/index.spec.tsx, src/components/SearchField/index.tsx, src/i18n/translations.ts, src/store/searchEngines/index.ts, src/store/store.ts
Add possibility to search the layer data via custom search engines (currently only Apache Solr is supported).
This search can be combined with already implemented nonimatim search - the configured engines can be (de)activated on demand via the settings menu in client. Additionally, the search query can be restricted by the visible map extent.
To get the things work, the search engines should be configured for the certain application via `toolConfig` as follows:
```
toolConfig: [
{...},
{
"name": "search",
"config": {
"engines": [
"nominatim",
"solr"
]
}
},
{...}
]
```
If no engines are configured, the `nominatim` search will be available by default to keep the existing client behaviour unchanged.
Using of the `solr` assumes that the search engine is available and the data index is …
=> Introduce multi search component

src/App.tsx, src/components/LayerDetailsModal/LayerConfiguration/index.less, src/components/LayerDetailsModal/LayerConfiguration/index.spec.tsx, src/components/LayerDetailsModal/LayerConfiguration/index.tsx, src/components/LayerDetailsModal/LayerDetails/index.less, src/components/LayerDetailsModal/LayerDetails/index.spec.tsx, src/components/LayerDetailsModal/LayerDetails/index.tsx, src/components/LayerDetailsModal/index.less, src/components/LayerDetailsModal/index.spec.tsx, src/components/LayerDetailsModal/index.tsx, src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/i18n/translations.ts, src/store/layerDetailsModal/index.ts, src/store/store.ts
This introduces the `LayerDetailsModal` presenting asorted entries of the `Capabilities` document of the given layer as well as the internal SHOGun configuration object.
=> Introduce layer details modal

package-lock.json, package.json, src/components/MultiSearch/index.tsx, src/utils/generateSolrQuery.spec.ts, src/utils/generateSolrQuery.ts
Instead of always searching through all the indexed solr data, this dynamically creates a solr search query based on the following layer attributes:
- `searchable` - only layers where this is `true` will be considered in the search
- `searchConfig`
- `attributes` - only layer attributes specified in this array will be included in the search query
- if `attributes` is not specified, all attributes will be included
Related PRs:
- https://github.com/terrestris/shogun/pull/703
- https://github.com/terrestris/shogun-util/pull/363
=> generate search query based on search configuration

README.md, resources/config/gis-client-config.js, src/bootstrap.tsx, src/components/EditFeatureDrawer/EditFeatureSwitch/index.tsx, src/components/EditFeatureDrawer/index.tsx, src/global.d.ts, src/hooks/useWriteWfsTransaction.ts
This makes the usage of WFS LockFeature during feature editing sessions configurable (disabled by default).
=> Configurable WFS LockFeature

src/components/PrintForm/index.tsx
This PR uses `customPrintScales` from the defined map scales to keep the print scales and map scales in sync.
=> Use custom print scale from map scales

src/components/Footer/index.less, src/components/ToolMenu/FeatureInfo/FeaturePropertyGrid/index.less, src/components/ToolMenu/FeatureInfo/FeaturePropertyGrid/index.tsx, src/i18n/translations.ts
* Set min width on scale combo to prevent cropped values for small scales (long numbers)
* Prevent ugly breaking of footer labels on middle/small devices
* Several feature grid enhancements
* Try to detect a geom field by some common names like `the_geom` or `geometry` and remove them from grid 
* Introduce further copy button (similar to "copy as GeoJson") which allows to copy shown feature attribute as KVP without geometry.
* Add line breaks to prevent cropped labels on log attributes
* Add some missing translations
=> Several layout enhancements for footer and feature info grid components

src/App.tsx, src/components/BasicMapComponent/index.tsx, src/hooks/useRestoreTransientLayers.ts
- introduces a new hook `useRestoreTransientLayers` which reads application state information from a provided permalink and restores the contained layers (uploaded / external layers)
- fixes a bug which resulted in duplication of external layers whenever the language was changed while a permalink was active
- dispatches a `change:layers` event when the language is changed
- this is needed to update the layer group names in the layer tree
=> Prevent layer duplication from permalink on language change

src/components/WmsTimeSlider/index.tsx
The new WMST layer uses '_' instead of 'value', so a new check was necessary.
=> fix: adjusting to new wmst properties

src/components/ToolMenu/Draw/index.tsx
Under some circumstances (e.g. Windows OS) the `type` might be empty. This adds a check for a proper file extension.
=> Fix GeoJSON upload of draw features

src/components/Footer/index.tsx
This applies the missing `key` props to all child components in the `Footer`.
=> Apply missing `key` props in `Footer` component

src/components/Header/index.less
This fixes the responsive header layout to show the application title for as long as possible.
=> Show app title on tablets as well

src/utils/generateSolrQuery.spec.ts, src/utils/generateSolrQuery.ts
This fixes the generated solr query when searching over multiple attributes. Previously, these were joined by `AND`. This meant that that the search term had to be in all attributes at the same time, which does not make sense. Now, the parts for each attribute are joined by `OR`.
=> Fix searching over multiple attributes

.github/workflows/on-push-main.yml
This updates the pipeline to create and push an image for the current state of the `main` branch. The image is tagged as `main` and can be used for testing purposes.
=> Build image for current state of the main branch

src/components/MultiSearch/index.tsx
- consider `searchConfig.displayTemplate` when displaying search results
- when displayTemplate is not set: enables solr highlighting, which allows us to highlight the search result even if there are no exact matches 
- removes the `listPrefixRenderer` for now, because the same info is already displayed in the collapse title
- changes the solr parameters to the keys used by solr to make the search endpoint interchangeable
=> feat: configurable search result display

README.md, resources/config/gis-client-config.js, src/bootstrap.tsx, src/global.d.ts, src/i18n/translations.ts
This introduces a new client config parameter `enableFallbackConfig` which determines if the client should load the fallback configuration if no application configuration (because not set explicitly or not loaded correctly) is available.
It also fixes an issue with empty locales as `i18n` might not have been initialized in the `catch` block.
=> Make loading of the fallback application config configurable

src/components/MultiSearch/index.tsx, src/utils/generateSolrQuery.spec.ts, src/utils/generateSolrQuery.ts
- switches to the `edismax` query parser (https://solr.apache.org/guide/6_6/the-extended-dismax-query-parser.html)
- this allows us to specify the search fields via the Query Fields parameter (`qf`) and in return allows for a much shorter query
- bugfix for search highlighting when no search attributes are configured
=> Simplify searching over multiple attributes

src/bootstrap.tsx, src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.tsx, src/components/MultiSearch/index.tsx, src/global.d.ts, src/store/editFeature/index.ts
The configuration is extended so that only certain roles (`authorizedRolesForEditingGeometries`) can see the buttons for creating or editing geometries at all.
Additionally, the button in the `MultiSearch` for editing feature attributes is temporarily hidden.
=> Additional toolbar role config

src/components/LayerDetailsModal/LayerDetails/index.tsx
This fixes an error while parsing the BBOX.
=> LayerDetailsModal: NPE check

src/components/EditFeatureDrawer/EditFeatureForm/index.tsx
This MR adds a missing pre-check if the member variable `fieldProps` is present for the object `fieldCfg`
=> Adds missing pre-check for fieldProps

src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.tsx, src/components/EditFeatureDrawer/index.tsx, src/components/ToolMenu/FeatureInfo/FeatureInfoTabs/index.tsx, src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx, src/components/ToolMenu/FeatureInfo/index.tsx, src/i18n/translations.ts
- allows to switch to the edit feature form directly from GFI
Bugfixes:
- sets formDirty when geometry is modified
- skip exit confirmation in edit feature form if form is not dirty
- minor fixes
=> Add edit button to GFI toolbar

src/hooks/useWriteWfsTransaction.ts
- does not transmit geometry when user has insufficient permissions
=> Omit geometry in WFS transaction if user has insufficient permissions

package-lock.json, package.json, src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx
This is required to keep the existing id passed from the server.
Requires https://github.com/terrestris/react-geo/pull/3532
=> fix: don't clone the feature to keep the existing id intact

src/components/ToolMenu/FeatureInfo/FeatureInfoTabs/index.tsx
This MR adjusts the `FeaturInfoTabs` to always use first tab when a new feature info is triggered.
=> Uses first tab on feature info panel

src/components/ToolMenu/FeatureInfo/index.tsx
This MR update the `FeatureInfo` to use always the first layer tab when a new feature info is triggered
=> Uses always the first tab on new FI

src/components/PrintForm/index.tsx
Move dispatching of attribution custom param to own effect to avoid multiple print manager initialization.
=> fix: fix dispatching of attribution custom param in print form

package-lock.json, package.json, src/bootstrap.tsx, src/components/ToolMenu/FeatureInfo/FeatureInfoTabs/index.tsx, src/components/ToolMenu/FeatureInfo/FeaturePropertyGrid/index.tsx, src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx, src/components/ToolMenu/FeatureInfo/index.tsx, src/components/ToolMenu/index.tsx, src/store/featureInfo/index.ts, src/store/store.ts
See title
This PR contains a *breaking change*: The `enabled` state is now handled in a new `featureInfo` slice.
In shogun-admin, the copy tools can be provided as follows:
```
...
{
"name": "feature_info",
"config": {
"visible": true,
"activeCopyTools": [
"COPY_AS_OBJECT"
]
}
},
...
```
=> Feature info: make copy tools configurable via tool-config in admin

src/components/ToolMenu/Draw/index.tsx, src/i18n/translations.ts
On a successful upload a message will appear informing the user about a successful upload.
On an error, a error message will appear informing the user, that only .geojson files can be uploaded.
=> Draw upload: error handling and userinformation

src/components/EditFeatureDrawer/EditReferenceTable/index.tsx, src/hooks/useWriteWfsTransaction.ts
This PR fixes a file upload bug in `EditReferenceTable` component.
The logic is updated to handle `FileInfoList` objects properly and manage empty arrays for file uploads. Thanks @dnlkoch 
@terrestris/devs please review.
=> Upload validation fix

src/components/ToolMenu/Draw/index.less, src/components/ToolMenu/Measure/index.less, src/components/ToolMenu/index.less
This MR changes the color of the active Button within the toolbar.
Instead of a default Black the secondary color is now used, which can be adjusted dynamically via the admin-client.
=> Tool menu layout

package-lock.json, package.json, src/components/ToolMenu/FeatureInfo/index.tsx
Refined fetch options in `FeatureInfo` to accept a function returning options based on WmsLayer.
Needs https://github.com/terrestris/react-geo/pull/3654 to be released in a new version of react-geo.
=> Update fetch options in FeatureInfo component

src/components/Permalink/index.tsx, src/i18n/translations.ts
Removes twitter from permalink share temporally since its now renamed and a x-icon is not existing yet.
=> feat: remove twitter from permalink

src/components/ToolMenu/index.tsx
With this PR, all competing actions are removed. This means that of the 4 tools "Measure", "Draw", "Query MapFeatures" and "Print", only one map interaction is active at a time.
=> Removes all competing actions in the map tools

src/components/PrintForm/index.tsx
During normal usage of the `PrintForm`, the fields are already reset when a new print is  configured. However, if `PrintForm` was used as a plugin, this action did not take place and remarks, titles, etc. from a previous print were still present in the fields and had to be removed or adjusted manually. 
With this PR the form fields are now also reset when used as a plug-in for a new print.
=> Reset print form fields

.github/workflows/release.yml
An automatically generated GitHub token seems to be required (see also: https://github.com/cycjimmy/semantic-release-action?tab=readme-ov-file#usage). This PR inserts the `GITHUB_TOKEN` secret into the release workflow.
=> Use github token for release workflow

src/bootstrap.tsx, src/components/ToolMenu/FeatureInfo/index.tsx
Using the following `feature_info` configuration in SHOGun-admin
```
{
"name": "feature_info",
"config": {
"visible": true,
"activeCopyTools": []
}
}
```
its possible now to deactivate all copy tools in `PaginationToolbar` if required
=> Allow empty array of copy tools in FeatureInfo

Dockerfile.dev, webpack.dev.js
This updates the webpack development server configuration by:
- changing the protocol from `https` to `http` (in the [recommended setup](https://github.com/terrestris/shogun-docker) it's proxied by a https server anyway).
- fixing the websocket client path to match the location given in the [nginx](https://github.com/terrestris/shogun-docker/blob/main/shogun-nginx/dev/default.conf#L95) proxy.
- setting the http port to 8080 (not needed in particular to be honest).
Together with [PR 92](https://github.com/terrestris/shogun-docker/pull/92) this fixes the need to manually confirm the development certificate for the web socket connection.
=> Fix development server websocket configuration

src/components/ToolMenu/FeatureInfo/FeatureInfoForm/index.tsx
This is needed because `form.setFieldsValue()` will not override null values when switching to another feature.
=> Reset form fields before setting values

src/components/ToolMenu/Draw/index.tsx, src/components/ToolMenu/index.tsx, src/i18n/translations.ts
This commit changes the order of the draw tool components. The order prioritizes drawing, altering drawings, deleting and finally exporting/importing. Also the logos of some components were changed since they did not fit to the functionality of the component or the logo was used multiple times.
=> Draw tool redesign

src/components/ToolMenu/LayerTree/index.less
By this PR `overflow` is added to treenode content in order to add scroll bar for legends as an example exceeding the LayerTreePanel width.
=> fix: allow overflow for treenode-content

src/bootstrap.tsx
See title.
This loads Polish and Czech `antd` locales if required in client.
=> fix: support Polish and Czech as default language

src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.tsx
This updates the `onDrawEnd` function of the `EditFeatureGeometryToolbar`.
It is kind of hackish to add a once listenere to the source but the code of the [react-geo/DrawButton](https://github.com/terrestris/react-geo/blob/main/src/Button/DrawButton/DrawButton.tsx#L125-L135) automatically assigns the digitizeLayer so the drawn feature is allways added. Usually it is possible to use the DrawInteraction without source to manually handle what should happen with the drawn features.
=> Update onDrawEnd to really replace the geometry

README.md, package-lock.json, package.json, src/bootstrap.tsx, src/context/SHOGunAPIClientContext.tsx, src/global.d.ts, src/i18n/translations.ts
This PR introduces two new config parameters, that allow to load the application configuration and the layers from other URLs. This way the client can be used without a shogun backend.
The config parameters are:
* `staticAppConfigUrl`
* `layerConfigUrl`
=> feat: allow static configurations without calling shogun

package-lock.json, package.json, src/bootstrap.tsx, src/components/BasicMapComponent/index.tsx, src/plugin/index.ts, src/store/store.ts
and bump @reduxjs/toolkit from 1.9.7 to 2.2.3.
The addition of further middlewares is required especially when [`rtk-query`](https://redux-toolkit.js.org/rtk-query/overview)  is used of redux-toolkit.
=> feat: allow addition of middlewares in plugin definition

src/components/ToolMenu/Draw/Attributions/AttributionRow/index.less, src/components/ToolMenu/Draw/Attributions/AttributionRow/index.tsx, src/components/ToolMenu/Draw/Attributions/index.less, src/components/ToolMenu/Draw/Attributions/index.tsx, src/components/ToolMenu/Draw/index.tsx, src/i18n/translations.ts
This fixes the attribute editor of the `draw` tools: 
- Allow adding multiple rows at once (without the need to save the feature first).
- Don't delete the attribute directly on the feature.
- Remove unneeded state copy of the feature attributes
- Show all available attributes in a dropdown
=> Multiple fixes to the attribute editor

jest.config.js, src/bootstrap.tsx, src/components/AddLayerModal/index.tsx, src/components/EditFeatureDrawer/index.tsx, src/components/LayerDetailsModal/index.tsx, src/components/MapDrawer/index.tsx, src/components/StylingDrawer/index.tsx, src/components/ToolMenu/Draw/StylingDrawerButton/StylingComponent/index.tsx, src/components/ToolMenu/LayerTree/index.tsx, src/components/ToolMenu/index.tsx, src/components/UploadDataModal/index.tsx
This PR fixes 3 types of SonarQube detected code smells:
* No duplicated key in the Jest config => dfd44be857b75c4ec78beb7244ec9972b8efcc21
* using `[].forEach` and not `[].map` in one instance => 59f0d60c3b101874c9884d263331404561dde8dd
* not using type intersections like `export type HumptyProps = {} | SomeOtherProps` or `export type HumptyProps = {} | Partial<SomeOtherProps>` => c77d18325bec2bcec0b2d7390bde7db19d5f0875
WRT the first two commits above I am quite quite sure they do the correct thing™
I am not so sure about the effects of c77d18325bec2bcec0b2d7390bde7db19d5f0875. @dnlkoch nodded an OK after a quick 15 seconds explanation around the coffee machine ;-)
Please review.
=> Fix several code smells that a SonarQube check identified

.github/workflows/on-push-main.yml
The variable 'Version' could not be used since it was not taken from env.
=> ci: use Version varable from env

src/App.less
This fix makes use of the secondary color variable for the attribution control button.
I chose the --secondary-color instead of a default (like white or black) since the background color is customizable too.
=> Coloring ol-control

resources/public/index.ejs, src/bootstrap.tsx
This MR uses the logo defined under 'logoPath' within the client-config as a loading image.
It is also saved within the cookies to ensure a faster image loading process.
co authored by @AmandaTamanda & Noémie
=> feat: make loading mask configurable

src/components/ToolMenu/index.less, src/components/ToolMenu/index.tsx
This PR allows to dynamically change the width of the menu toolbar. The width of the menu toolbar is now only set in the ToolMenu/index.tsx file and not in the ToolMenu/index.less file.
From ticket [#21431](https://redmine.intranet.terrestris.de/issues/21431?include=journals&journals=all)
Please review @dnlkoch
=> feat: adds dynamic width to menu toolbar

src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx
This moves the setting of initial values above the `resetFields` call. As `resetFields` resets the form to the initial values. In the current state these are the intialValues of the previously used feature.
=> Fix resetting the `EditFeatureFullForm`

src/components/ToolMenu/index.less, src/components/ToolMenu/index.tsx
This PR is a follow-up of [PR 1563](https://github.com/terrestris/shogun-gis-client/pull/1563) and fixes the highlighting of the text by disabling it in the less-file as well as setting the width to its previous value (before collapsing) when (re)opening the drawer by clicking on one of the icons. 
Please review @dnlkoch :)
=> fix: fixes of dynamic width of toolbar

src/components/MultiSearch/index.tsx, src/utils/generateSolrQuery.spec.ts, src/utils/generateSolrQuery.ts
This groups solr queries by the provided list of query fields. This means all queries with identical query fields (= search attributes) will be bundled in a single request.
=> Grouped solr queries

src/components/ToolMenu/LayerTree/index.less, src/components/ToolMenu/LayerTree/index.tsx
Loading indicator now looks like this:
=> fix: fixes loading indicator and adjusts spacing

src/components/ToolMenu/LayerTree/index.less
=> Fix LayerTree overflow styling

src/App.less
This should enhance visibility.
The Button now goes along with the font color of the other buttons:
=> Ol-Attribution

src/components/UserMenu/index.tsx
This redirects to the login page after logging out instead of reloading the client which may case an unexpected "You're not allowed to see this application" error.
=> Redirect to login after logout

src/bootstrap.tsx
This allows disabling of specific plugins via shogun appConfig. To disable a plugin for a certain application you can add this to your toolconfig:
```json
{
"name": "utility-survey-admin-plugin",
"config": {
"disabled": true
}
}
```
The `name` has to match the `key` of the plugin as configured in the `plugin.ts`.
=> Allow disabling plugins via appConfig

src/components/ToolMenu/index.tsx
ToolMenu should be collapsed when starting mobile application as described in [#22048](https://redmine.intranet.terrestris.de/issues/22048?include=journals&journals=all)
view when starting in mobile version now:
Please review :)
=> fix: adjust width in mobile version

src/bootstrap.tsx, src/components/ToolMenu/LayerTree/index.tsx, src/components/ToolMenu/index.tsx, src/store/layerTree/index.ts, src/store/store.ts
This PR makes the uploading options in the layer tree configurable by setting:
"name": "tree",
"config": {
"visible": true,
"uploadTools": [
"addWMS",
"dataUpload"
]
}
in the tool config in shogun-admin as described in [#22030](https://redmine.intranet.terrestris.de/issues/22030?include=journals&journals=all)
Different upload options are visible depending on the tool-configuration in shogun-admin:
Please review :)
=> feat: make upload options configurable

.github/workflows/on-pull-request.yml
This merge request edits the on-pull-request pipeline. The coverage comment is now edited when there are no tests found related to the files changed.
=> ci: fix coverage-comment for changed files

src/utils/generateSolrQuery.spec.ts, src/utils/generateSolrQuery.ts
Problem: When many layers are grouped together into a single query, the query may be too large for solr, resulting in the following error:
`org.apache.lucene.search.IndexSearcher$TooManyNestedClauses: Query contains too many nested clauses; maxClauseCount is set to 1024`
This queries feature types in a separate condition. This way, search parts do not have to be duplicated for each feature type, reducing the overall query length.
Further adjustments:
- reworks the the wildcard and proximity search, reducing its length slightly
- gives the exact search term the highest boosting value instead of the lowest
@terrestris/devs Please review.
=> Simplify solr query for multiple feature types

.github/workflows/on-push-main.yml, sonar-project.properties
Minor fix updating the report path and base path used by SonarQube to make sure the SonarQube-Scan is carried out correctly and the report path matches the coverageDirectory specified in jest-config.
Currently test results can not be read by SonarQube resulting in missing coverage results:
=> ci: adjust paths for sonarqube scan

src/components/MultiSearch/index.less
The collapsible panel had a max height of 400px. If there were more results than that, they would not be displayed properly.
@terrestris/devs Please review.
=> Fix search result display overflow

.github/workflows/on-pull-request.yml
This merge request changes how the jest-tests related to current changes are run, using the `--changedSince`-Option, instead of -`-onlyChanged` since onlyChanged seems to include only diffs from the previous commit, while changedSince includes all diffs from main.
In order for this to work, a local branch is first created based on origin/main, since actions/checkout does checkout only the code relevant to the PR. The changed files are identified based on this local branch.
=> ci: update jest test for changed files to use changedSince

resources/config/gis-client-config.js, src/components/MultiSearch/index.tsx, src/global.d.ts
When clicking on a search result, the selected layer is automatically activated in the layer tree. This prevents having to search for the layer manually.
The behavior is configurable by setting `clientConfig.search.activateLayerOnClick`
@terrestris/devs Please review.
=> Activate layer on search result click

src/components/ToolMenu/index.tsx
Replaces arrow icon with info icon.
Before:
Now:
@terrestris/devs Please review.
=> Use info icon for feature info tool

src/bootstrap.tsx, src/components/ToolMenu/LayerTree/index.tsx, src/store/layerTree/index.ts
This PR adds an option to set the layer legends visible by default when the layer is visible, so you don't need to select the legend in the context menu. 
Settings in the tool-config in SHOGun-Admin:
{
"name": "tree",
"config": {
"showLegends": false,
"visible": true
}
},
changing the showLegends config to true gives this initial view in the SHOGun-Gis-Client:
Please review :)
=> feat: show legends per default

src/components/MultiSearch/index.tsx
- sets layer visibility on search result click
- also sets visibility of parent layer groups
- collapse search result panel
=> Set layer visibility on search result click

src/components/DocumentationButton/index.tsx, src/components/Header/index.tsx, src/components/UserMenu/index.tsx
=> feat: Introduce docs button

src/components/DisplayField/index.spec.tsx, src/components/DisplayField/index.tsx
This MR masks an URL if a property `maskedUrl` is set within the `featureInfoFormConfig`. 
If that Property is not set the default value will be shown.
=> Masked-URL

package-lock.json, package.json, watchBuild.js
**Attention:** targets the [update-dependencies-for-ol-and-react](https://github.com/terrestris/shogun-gis-client/tree/update-dependencies-for-ol-and-react) branch!
This replaces `watch` with `chokidar` in the `watchBuild.js` to fix several high audit findings. 
=> Replace `watch` with `chokidar`

.releaserc.json
This enables releases from the `next` and `8.x` branches.
=> Enable releases from next and 8.x branches

resources/template/index.ejs, rspack.common.js
**Attention:** targets the [update-dependencies-for-ol-and-react](https://github.com/terrestris/shogun-gis-client/tree/update-dependencies-for-ol-and-react) branch!
This fixes some minors in the index page:
- show the favicon again
- check if an `appId` is actually available (which is optional)
- show the loading icon
=> Index page fixes

src/components/PrintForm/CustomFieldInput/index.tsx, src/components/PrintForm/index.tsx
Keeps the users desired cursor position in the react input element instead of springing to the end of the input field
=> fix: cursor jumps on keystroke

src/components/AddLayerModal/index.tsx, src/components/ToolMenu/LayerTree/index.tsx
If the first layer is added to the map in the `AddLayerModal` (and the "External layers" folder is not present in the tree yet) the layer isn't visible in this folder. This fixes this issue by adding the layer to the target group before adding it to the map (to make all event listeners in the react-geo layer tree work as needed).
=> `AddLayerModal`: Show layer in tree after adding it to the map

package-lock.json, package.json, src/bootstrap.tsx
This adds the missing piece to parse the [configurable mapInteractions](https://github.com/terrestris/shogun/pull/942).
It updates the shogun-util to version [10.1.0](https://github.com/terrestris/shogun-util/releases/tag/v10.1.0) which includes the parsing part.
=> Parse `mapInteractions`

src/bootstrap.tsx, src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.less, src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.tsx
Sets geometry edit tools as inactive until activated by the users and applies styling fixes.
=> fix: geometry edit tools and styling

src/bootstrap.tsx, src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/store/layerTree/index.ts
This PR adds a configuration to the tree in the tool-config (in shogun-admin) in order to display the metadata of the layers or not.
Adding "metadataVisible": true or not indicating this configuration gives 
Adding  "metadataVisible": false gives 
Please review :)
=> fix: make metadata configurable

src/bootstrap.tsx, src/components/RerouteToLogin/index.tsx, src/i18n/translations.ts, src/index.less
Adds reroute link from error page to login
=> Reroute to login page

src/bootstrap.tsx
Since the we don't set the deprecated `shortcut icon` anymore in the index template, the selector needs to be updated as well.
=> Readd support for a custom favicon path

src/components/EditFeatureDrawer/EditFeatureFullForm/index.tsx, src/components/ToolMenu/FeatureInfo/FeaturePropertyGrid/index.tsx, src/components/ToolMenu/FeatureInfo/index.tsx
for layers with `editable: true` the GFI edit button was disabled when **not** using a `featureInfoFormConfig`. This is a fix for this scenario.
Before: 
After:
=> fix: fix GFI edit button disabled status

src/components/DisplayField/index.tsx
Using a `featureInfoFormConfig` currently leads to such errors in case of simple string fields:
Having a look at the code, it seems that `getUpload` and `isJson` in the `DisplayField` class make use of "expected" fails when calling `JSON.parse`, so they can return `null`, respectively `false`.
We should not spam our console with "expected" parse errors, so i changed this from `error` to `trace` level, which is not even the default (as `debug` is). This should lead to a cleaner console using the GFI tool with `featureInfoFormConfig`
=> Only trace expected errors

.gitignore
This ensures that the `test-results` folder is also ignored as a folder in `src/e2e-tests/`
=> chore: ignore test-results in subpaths

src/components/ToolMenu/LayerTree/index.tsx
Create deep clone from state value before manipulating it.
Extracted from #1775.
=> Fix layer loading indicator in tree

src/components/ToolMenu/LayerTree/index.tsx
This fixes an unchecked cast which might result in an error since the `Legend` component does accept WMS layers only.
=> Show legend for WMS layers only

src/components/ToolMenu/FeatureInfo/index.tsx
This (re)enables `drillDown` in the `FeatureInfo` component thus querying all stacked layers.
=> Reactivate drill down feature info requests

src/components/ToolMenu/LayerTree/index.tsx
This prevents the `Legend` from unneeded rerenders (and annoying loading indicators in it) by caching the props `extraParams` and `headers`.
Before:
After:
=> Prevent unnecessary rerenders of the legend

src/components/ToolMenu/LayerTree/index.less
This MR fixes the CSS of the layertree checkboxes.
The initial CSS got changed in antd so it needs to be overwritten using `!important`
=> fix: layertree checkbox css

package-lock.json, package.json, src/bootstrap.tsx, src/i18n/translations.ts
This MR makes use of the new api endpoint `/name/applicationName`.
But for this to work, the new SHOGun-Util Version featuring the following [MR](https://github.com/terrestris/shogun-util/pull/867) needs to be used.
This MR will remain as a Draft until the new shogun-util is deployed and used within this MR.
Please note:
the property `historyApiFallback` within the rspack.dev.js mostlikely needs to be set true.
=> feat: introduces the new api endpoint applicationName

src/components/ToolMenu/Draw/index.tsx
This fixes a warning about missing keys in the draw tool menu.
=> Add missing keys in list

src/bootstrap.tsx, src/components/DocumentationButton/index.tsx, src/components/Footer/index.less, src/components/Footer/index.tsx, src/components/Header/index.spec.tsx, src/components/Header/index.tsx, src/components/UserMenu/index.less, src/components/UserMenu/index.tsx, src/i18n/translations.ts, src/store/store.ts, src/store/userMenu/index.tsx
This suggests to move the application info opener ("About") from the user menu to the footer. This allows users to open it regardless from the presence of the user menu which visible state is defined as follows now:
- visible by default always, except (possibly required for public instances):
- not visible if Keycloak is disabled globally (see `keycloak.enabled`) -> no change in behaviour
- not visible if explicitly disabled for the given application configuration -> new configuration:
```
{
"name": "user_menu",
"config": {
"visible": false
}
}
```
The menu itself is slightly refactored to show a login button only if a user is not logged in already and to show the users full name as well. Previously the username was shown only.
In addition the `DocumentationButton` is slightly simplified. …
=> Move application info opener to footer

src/components/ToolMenu/LayerTree/index.tsx
Enabling the legend (in the layer tree) without having moved the map before might result in an erroneous or inaccurate `GetLegendGraphic` request since the map scale is `undefined`. 
This suggests to fix this issue by setting the default scale value to the current map scale. 
=> Legend: Set current map scale on initial render

package-lock.json, package.json, rspack.common.js
This adds proj4 as a singleton to the module federation plugin. This is needed when custom projections are registered to proj4 and proj4 is called directly.
=> feat: add proj4 to module federation

README.md
This adds sonarqube status badges to the README file.
=> docs: add sonarqube status to README

src/components/Header/index.less
This fixes a layout bug in Firefox where the left-items took all the space when containing a logo.
=> Update header layout

src/components/MapDrawer/index.tsx, src/components/MapToolbar/index.less, src/components/MapToolbar/index.tsx, src/components/StylingDrawer/index.tsx, src/components/ToolMenu/index.less, src/index.less
This adjusts the position of the map toolbar when a drawer is shown.
=> Move toolbar when drawer opens/closes

package-lock.json, package.json
See title. Required to get release of `next` branch running again
=> chore: adds missing rimraf dependency

.github/workflows/release.yml, .github/workflows/release_docker.yml
This attempts to fix the currently failing pipeline in the #1976 branch.
Explanation: As there is currently no release performed for the branch, the variable `release_version` is not defined and the checkout can't be performed. As fallback the previous version/tag is used now.
=> Fix pipeline for `next` branch without any new release

package-lock.json, package.json, src/App.tsx, src/components/EditFeatureDrawer/EditFeatureGeometryToolbar/index.tsx, src/components/MapToolbar/index.tsx, src/components/MultiSearch/index.tsx, src/components/SearchResultDrawer/AttributeValueCell/index.spec.tsx, src/components/SearchResultDrawer/AttributeValueCell/index.tsx, src/components/SearchResultDrawer/index.spec.tsx, src/components/SearchResultDrawer/index.tsx, src/components/StylingDrawer/index.less, src/components/StylingDrawer/index.tsx, src/components/ToolMenu/FeatureInfo/PaginationToolbar/index.tsx, src/components/ToolMenu/LayerTree/LayerTreeContextMenu/index.tsx, src/global.d.ts, src/hooks/searchEngines/useNominatimSearchEngine.ts, src/hooks/searchEngines/useSolrSearchEngine.ts, src/hooks/searchEngines/useWfsSearchEngine.ts, src/hooks/useGetFitPadding.ts, src/i18n/translations.ts, src/store/searchResult/index.tsx, src/store/store.ts
This introduces the SearchResultDrawer.
The feature can be enabled when setting [searchResultDrawer](https://github.com/terrestris/shogun-gis-client/compare/search-result-drawer?expand=1#diff-858566d2d4cf06579a908cb85f587c5752fa0fa6a47d579277749006e86f0834R38) to true in the `SearchConfig` of the gis-client-config.js.
When set to true the search result wil be displayed in a drawer on the right side.
It contains the "title" property of the selected feature of the `SearchResultList`.
When the passed feature has other properties then title a `PropertyGrid` with its features is shown.
TODO:
=> Introduces SearchResultDrawer

src/hooks/searchEngines/useWfsSearchEngine.ts
This adds support for numeric attributes in the WFS search and removes the unneeded blacklisting of attributes (it seems to be a leftover of the solr search this one is based upon).
=> Fixes for the WFS search

src/components/MultiSearch/index.tsx, src/components/SearchResultDrawer/index.tsx, src/hooks/searchEngines/useWfsSearchEngine.ts, src/store/searchResult/index.tsx
Previously only the given `attributes` of the layer's search configuration were requested from the WFS. This might resulted in unwanted behaviours e.g. while making the attribues `name` and `description` searchable, but making the attribute `owner` visible in the search result drawer as well. The latter wouldn't be available.
This fixes this issue by requesting all needed attributes from the WFS target layer.
In addition it removes the layer instance from the store since it's not serializable (well).
=> Request all required layer properties in search
